language:
- python
python:
- 2.7
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- python dewey_tests.py
- coverage run dewey_tests.py
before_deploy:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
deploy:
- provider: s3
  access_key_id: &1
    secure: EBehkimbDTTg9wr4F4FpEyrGfs1ZJ9iPMZE2gf6fLOFk23UH5GujogLl26z0Eitkn8I5CDWnM9EYLLRWNDHm4CSfIOwOOj6juuej+vFrIlQ8NOl5WgOzHW5pIGG1lbbhdQiGeedmTJUpQcUB3cN8p4SC3V2BsbDwByT9yFsJRLekOIiQk/iEDZWLdyRyRKCCYwOsEJ2u8Pgi+Eb2ZQD4ROismKI/2KdOchWM/+G0gySiogzxQfiIHYxEfSQyEIv3bX8RSngS7RdaEP02M3nS4Dj8ojc35d7kixCv/fggajXwJpaTuEGXUUKRGcjYGwlr8oPJZoVolvbnclgcIcoKdRSo+RMqVhdQirRSKk2zyyoi7O9A30XGv+pqYFpeL58w377QHxI9Al7i6n+/nZ5fhBmKDQ7TCUgmDPBao5qvBm3Ca/HKx1ownzjHiI9tUMCW6VAdYGLo/mUtDzRBnEiDGojyfpu/z/xmQWu8VmfHBBpSIgfnbx0aTWLLytGCbsqV+eoczzFTFA2twfxcDi9dtS59cddL0CQ9UahK9YPs2YQZZUG04+63jBNpgRHo+K96C8V1hTqetOW8C2pVX+/TBaCNeQ9s9hfwPWWSmF9kHxNyTbdB9CwRvYFxQfOkzNmwYpaM0XiDOt03TImp8s/z+pPeYdUHDzdkpcWUwnjTCBI=
  secret_access_key: &2
    secure: 3SNbIAVpiseBQEU5BiFpwV9G2K9ZFORC+V7mift1Y+wRiunCXrWuaRb7yr+hHfxf/wgEMir46geKV7HCmBu4svvdgRKENDmj7bv0mvUlLN3jvlF+BDzHNTFcCW0ZiTObf0LacEGN4W+63i1VqPBYNRy0a3AD62HRAjzbNW8JkMSPVYjGC/vTGKtab3ZyBS2S4MxTJgWbkc50TZ6g2UhkLxE5Tl/4QvACkF+uIEi0FCtuFOpcD68x3KhbQDPYtOSszJ+k2ikTTJeW2mQsleF+b6RK3wWvPKxQZLYsOmfVTg0jn6B2SGs5+iWRFCDqmF7jmgy3x1ImsV1DLQizBrfTlmxuy3p5RV7E8dVEUVB2ympWvAVRTMCTFeAaHAFlMO7ip2oA8frz8snm5FyNLc13E+sj+LQ/AaTwz3IbAiA40GrFQC7rmaG5JfVnotSoPlkeR4xhaZ6KYIaXlnvPlVSBJAtzWwPbll5/7wNi37apekubHpBr5n01SEaMX1W+T3nbvgnO+bJ1/ElCtEvJRca7udQ7vlrTlouUhk+V5Ot8KTJGSRBx28qKn4vD3elsdmPsTkPWQ8Cj4mw94+X91s8XzuzcDRVCzS1UFTN3hCN2dNZYA5+O3TWYJF0SPMUXppKiRJCp8+E9+beF1OJo0/bzJ4imeqQ9+N6dv2t1kttA+9E=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &3
    repo: camelspeed/dewey
  bucket: camelspeed-dewey
  region: us-west-2
- provider: codedeploy
  access_key_id: *1
  secret_access_key: *2
  bucket: camelspeed-dewey
  key: latest.zip
  bundle_type: zip
  application: camelspeed-dewey-webapp
  deployment_group: camelspeed-dewey-webapps
  region: us-east-1
  on: *3
after_success:
- coveralls

